# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:          pretty

# Setup
title:              noinnion
tagline:            'A Jekyll theme'
description:        'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                http://noinnion.com
baseurl:            ''
repository:         noinnion/noinnion.github.io
excerpt_separator:  <!--more-->

# Custom vars
version:            1.0.0

# Plugins
plugins_dir:        [jekyll-picture-tag]

# Conversion
markdown:           redcarpet

# Pagination
gems:               [jekyll-paginate]
paginate:           6
paginate_path:      "blog/page:num"

# About/contact
author:
  name:             noinnion
  url:              https://twitter.com/noinnion
  email:            noinnion@gmail.com

# Collections
collections:
  pages:
    output:         true
    permalink:      /:title
  faqs:
    output:         true
    permalink:      /:collection/:name    

defaults:
  -
    scope:
      path:         "" 
      type:         pages
    values:
      layout:       page



# Jekyll-Picture-Tag
picture:
  source:           assets/img/_fullsize
  output:           assets/img
  markup:           picture
  presets:
    # Full width pictures
    default:
      ppi:          [1, 1.5]
      attr:
        class:      blog-full
        itemprop:   image
      source_lrg:
        media:      "(min-width: 40em)"
        width:      1024
      source_med:
        media:      "(min-width: 30em)"
        width:      800
      source_default:
        width:      420
    # Self-set resolution sources. Useful if you don't want a 1:1 image size to dppx ratio.
    gallery:
      source_wide_hi:
        media:      "(min-width: 40em) and (min-resolution: 1.5dppx)"
        width:      900
        height:     600
      source_wide:
        media:      "(min-width: 40em)"
        width:      600
        height:     400
      source_default:
        width:      250
        height:     250